### ISSUE TITLE
Allow access to response headers

### ISSUE THREAD

**Issue by Minnozz** [bloodyowl/rescript-request#1]
The underlying `XMLHttpRequest` has a `getResponseHeader()` method to access response headers. Could the response headers be exposed in any way?

**Comment by bloodyowl** [comment]
Would it be ok to you if the response record type had an `xhr: 'a` property?

**Comment by Minnozz** [comment]
That would work for me, if you don't mind exposing that `XMLHttpRequest` is used internally.

**Comment by bloodyowl** [comment]
Released in rescript-request@2.0.0
